apiVersion: v1
kind: ConfigMap
metadata:
  name: postech-api-config
  namespace: default
data:
  APP_ENV: "production"
  APP_PORT: "8080"
  APP_SECURE: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postech-api-deployment
  labels:
    app: postech-api
spec:
#  replicas: 3 # Configuração para 3 réplicas
  selector:
    matchLabels:
      app: postech-api
  template:
    metadata:
      labels:
        app: postech-api
    spec:
      containers:
      - name: postech-api-container
        image: wferreirasp/postech-api-consulta:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        envFrom:
        - configMapRef:
            name: postech-api-config
#        volumeMounts:
#        - name: app-config
#          mountPath: /app/config # Monte o volume em um diretório dentro do container
#      volumes:
#      - name: app-config
#        configMap:
#          name: postech-api-config # ConfigMap vinculado como volume

---

apiVersion: v1
kind: Service
metadata:
  name: postech-api-service
spec:
  selector:
    app: postech-api
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8080
  type: NodePort
