apiVersion: v1
kind: ConfigMap
metadata:
  name: postech-api-config
data:
  ConnectionStrings__ConnectionStringSql: "Data Source=host.docker.internal,1433;Initial Catalog=postech_fase1;User ID=${DB_USERNAME};Password=${DB_PASSWORD};TrustServerCertificate=True"