apiVersion: apps/v1
kind: Deployment
metadata:
  name: postech-api-deployment
  labels:
    app: postech-api
spec:
  selector:
    matchLabels:
      app: postech-api
  template:
    metadata:
      labels:
        app: postech-api
    spec:
      containers:
      - name: postech-api-container
        image: wferreirasp/postech-api-consulta:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        envFrom:
        - configMapRef:
            name: postech-api-config
        - secretRef:
            name: postech-db-credentials
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: appsettings-volume
        configMap:
          name: postech-api-config



