name: CI-CD Pipeline do Grupo 25

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                solution-path: ['./Fase 4/PosTech.Grupo25.Fase4']

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Setup .NET 8.x
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.x'

            - name: Instalando dependências
              working-directory: ${{matrix.solution-path}}
              run: dotnet restore

            - name: Build da aplicação
              working-directory: ${{matrix.solution-path}}
              run: dotnet build

#            - name: Testes Unitário/Integração
#              working-directory: ${{matrix.solution-path}}
#              run: dotnet test

            - name: Login no Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Construir a imagem Docker - API Consulta
              working-directory: ${{ matrix.solution-path }}
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/postech-api-consulta:latest -f Dockerfile-consulta .

            - name: Fazer push da imagem para o Docker Hub - API Consulta
              run: docker push ${{ secrets.DOCKER_USERNAME }}/postech-api-consulta:latest
              
            - name: Construir a imagem Docker - API Cadastro
              working-directory: ${{ matrix.solution-path }}
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/postech-api-cadastro:latest -f Dockerfile-cadastro .

            - name: Fazer push da imagem para o Docker Hub - API Cadastro
              run: docker push ${{ secrets.DOCKER_USERNAME }}/postech-api-cadastro:latest
              
            - name: Construir a imagem Docker - API Alteração
              working-directory: ${{ matrix.solution-path }}
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/postech-api-alteracao:latest -f Dockerfile-alteracao .

            - name: Fazer push da imagem para o Docker Hub - API Alteração
              run: docker push ${{ secrets.DOCKER_USERNAME }}/postech-api-alteracao:latest
              
            - name: Construir a imagem Docker - API Exclusão
              working-directory: ${{ matrix.solution-path }}
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/postech-api-exclusao:latest -f Dockerfile-exclusao .

            - name: Fazer push da imagem para o Docker Hub - API Exclusão
              run: docker push ${{ secrets.DOCKER_USERNAME }}/postech-api-exclusao:latest
