name: CI/CD Pipeline do Grupo 25

on:
    push:
        branches:
            - main
            - gh_actions

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Setup .NET 8.x
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.x'

            - name: Instalando dependências
              run: dotnet restore

            - name: Build
              run: dotnet build

            - name: Teste
              run: dotnet test